# Generated by Django 4.0.4 on 2022-04-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('brand', models.CharField(choices=[('INT', 'INTEL'), ('AMD', 'AMD')], default='INT', max_length=3, verbose_name='brand')),
            ],
            options={
                'verbose_name': 'processor',
                'verbose_name_plural': 'processors',
            },
        ),
    ]
